services:
  - type: web
    name: fynd-feedback-backend
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
