services:
  - type: web
    name: fynd-feedback-backend
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GROQ_API_KEY
        sync: false
