services:
  - type: web
    name: fynd-user-dashboard
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_user_app.py --server.port $PORT --server.address 0.0.0.0"
